#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Spark Arena
# SPDX-License-Identifier: Apache-2.0
"""Collect license and notice files from modules actually linked into the binary."""
import argparse
import json
import os
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
# License collection covers candidate Windows builds as well as the release
# targets. Listing target dependencies executes no foreign binaries.
decoder = json.JSONDecoder()
modules = {}
for target_os in ("linux", "darwin", "windows"):
    raw = subprocess.check_output(
        [os.environ.get("GO", "go"), "list", "-deps", "-json", "./cmd/oci-relay"], cwd=root, text=True,
        env=dict(os.environ, GOOS=target_os, GOARCH="arm64", CGO_ENABLED="0"),
    )
    while raw.strip():
        value, end = decoder.raw_decode(raw.lstrip())
        raw = raw.lstrip()[end:]
        module = value.get("Module", {})
        if module and not module.get("Main"):
            if module.get("Replace"):
                raise SystemExit("Release license collection rejects replaced modules")
            modules[module["Path"]] = module
sections = ["Third-party license and notice texts for OCI Relay.\nGenerated by scripts/dependency-licenses.py.\n"]
goroot = Path(subprocess.check_output([os.environ.get("GO", "go"), "env", "GOROOT"], text=True).strip())
sections.append("\nGo standard library/runtime\n\n" + (goroot / "LICENSE").read_text().rstrip() + "\n")
for name, module in sorted(modules.items()):
    directory = Path(module["Dir"])
    candidates = sorted(
        p for p in directory.iterdir()
        if p.is_file() and p.name.upper().startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE"))
        and p.suffix.lower() not in {".go", ".py"}
    )
    if not candidates:
        raise SystemExit("Missing license for " + name)
    sections.append("\n" + "=" * 78 + "\n" + name + " " + module["Version"] + "\n")
    for path in candidates:
        sections.append("\n--- " + path.name + " ---\n" + path.read_text().rstrip() + "\n")
output = "\n".join(sections)
destination = root / "THIRD_PARTY_LICENSES.txt"
if args.check:
    if not destination.is_file() or destination.read_text() != output:
        raise SystemExit("THIRD_PARTY_LICENSES.txt is stale; run scripts/dependency-licenses.py")
else:
    destination.write_text(output)
print("Verified license texts for", len(modules), "linked dependency modules")
